[template.environment]
  GQL_HOST = "https://app13958-trial.cloudwayssites.com/graphql"
  NUXT_IMAGE_DOMAINS = "https://app13958-trial.cloudwayssites.com/graphql"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
